git:
  depth: 1
addons:
  apt:
    packages:
      - docker-ce
      - curl
services:
    - docker

os: linux

language:
  - cpp

branches:
  only:
      - develop
      - static_checker
      - hotfix

jobs:
  include:
    - name: Library Tests
      script:
        - docker run --rm -u root -v $PWD:/OpenRSR-OF7 foamscience/bionic-openfoam7 /bin/bash -i -c /OpenRSR-OF7/scripts/docker_build.sh
