#!/bin/sh

libs="rsr\
    relativePermeabilityModels\
    capillaryPressureModels\
    wellModels"
root=$PWD

# Clean libraries
for lib in $libs; do
    wclean $root/src/$lib
done

# Clean all solvers
#wclean all solvers
