#!/bin/sh
# This script should be invoked from the root directory of he toolkit
# Run twice to get a list of compiled shared objects

check_errs()
{
  # Parameter 1 is the return code
  # Parameter 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "ERROR # ${1} : ${2}"
    exit ${1}
  fi
}

root=$PWD

# Compile Third-party libraries
$root/ThirdParty/Allwmake

# Compile OpenRSR libraries
libs="rsr\
    relativePermeabilityModels\
    capillaryPressureModels\
    wellModels\
    functionObjects\
    "

# Compile libraries
for lib in $libs; do
    echo "--------------------------------------------"
    echo "Compiling library: $lib"
    echo "--------------------------------------------"
    wmake libso $root/src/$lib
    check_errs $? "Library $lib didn't compile ... ugh"
done

# Compile all solvers
echo "--------------------------------------------"
echo "Compiling all solvers"
echo "--------------------------------------------"
wmake -all $root/applications/solvers
